### ISSUE TITLE
default policy of sanitize all

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/go-k8s-process#108] opened 2021-07-13 12:02 UTC
Setting the default policy to sanitize for all possible options.

Issue - some policies are set to allow:
  <pptConfig>
    <macros>sanitise</macros>
    <metadata>allow</metadata>
    <embedded_files>allow</embedded_files>
    <review_comments>allow</review_comments>
    <internal_hyperlinks>allow</internal_hyperlinks>
    <external_hyperlinks>allow</external_hyperlinks>
  </pptConfig>

**Comment by Lestat06** [comment] 2021-07-15 17:14
this is OK now for filedrop

**Comment by Lestat06** [comment] 2021-07-15 17:25
also duplicate of this https://github.com/k8-proxy/cs-k8s-api/issues/476

**Comment by Lestat06** [comment] 2021-07-18 20:24
this is fixed in develop for filedrop
![image](https://user-images.githubusercontent.com/6232283/126081189-d98a2da3-0808-4348-8614-8cd1516167fc.png)

**Closed** 2021-07-23 19:35 UTC
Labels: P1, bug, v0.10.0
